### PR TITLE
fix xarray deps

### PR DESCRIPTION
**Pull request by ocefpaf**
Addresses https://github.com/pangeo-data/xESMF/issues/57

### CODE REVIEW

**Comment by jthielen** [comment]
Thank you @ocefpaf! It looks like this also supersedes https://github.com/conda-forge/xesmf-feedstock/pull/11.

**Comment by ocefpaf** [comment]
Actually I thought that release v0.5.0 had the != but it is <=, see https://github.com/pangeo-data/xESMF/blob/bb29347acd244ec7e3f9b50773d08a19803e4a16/setup.py#L22

@huard and @jthielen we probably need a new release then, no? Unless the pin was not OK in the current version to stat with.

**Comment by jthielen** [comment]
As a user I wouldn't mind either way forward, so I'll defer to @huard (and the other current xesmf maintainers @raphaeldussin and @andersy005?).

**Comment by huard** [comment]
v0.5.1 released

**Comment by raphaeldussin** [comment]
@huard we don't have the package for 0.5.1 only the sources (tar and zip) in assets. how do we fix this? sorry @ocefpaf I'll update the sha when we got this fixed

**Comment by ocefpaf** [comment]
> @huard we don't have the package for 0.5.1 only the sources (tar and zip) in assets. how do we fix this? sorry @ocefpaf I'll update the sha when we got this fixed

Just did that manually, fixed the checksum, and I sent a PR to fix the error that prevented the package from being created. See https://github.com/pangeo-data/xESMF/pull/63

**Pull request merged**
