### PR TITLE
DEP: Avoid ESMPy 8.4.*

### LINKED ISSUE #43: xESMF can pull in unimportable ESMPy 8.4.* as dependency
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

ESMPy 8.4 changed from specifying authors in both `setup.py` and the package `__init__.py` to only in `setup.py`, using `importlib_metadata` to grab the metadata from the package `dist-info`, then moved the whole system to `pyproject.toml` with no `setup.py`, during which the list of authors got dropped but the code to get them from `dist-info` did not.  (esmf-org/esmf#58)

At the time, this was not an issue, as `importlib_metadata` produced a result of `None` when asked for metadata not provided by the package.  This changed to `DeprecationWarning`s, which prompted a fix before ESMPy 8.5 (esmf-org/esmf#140), and eventually to `KeyError`, which caused an `ImportError`.

This is already on the xESMF repo as pangeo-data/xESMF#374

Would it be possible to change the requirements from `ESMPy>=8.0` to `ESMPy>=8.0, !=8.4.0, !=8.4.1, !=8.4.2`?  I'm not sure where that gets set, or I'd make the PR myself.

### Installed packages
```
ESMPy==8.4.1
python==3.11
xesmf
pynio
```
### Environment info
```
Linux server
```

### PR DESCRIPTION
**Pull request by DWesl**
ESMPy 8.4.* imports only with old versions of importlib_metadata. With current versions of importlib_metadata, ESMPy fails to import.

Closes #43

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` 
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by aulemahal** [comment]
Two notes:
- esmf 8.4 is the last version available to windows users. This PR means that windows users will be stuck with <= 8.3 for the next xESMF releases. I'm not sure of the implications though...

- Looks like the latest xarray causes some problems with xESMF... I'll look into that.

**Comment by aulemahal** [comment]
I opened a PR for the xarray issue : https://github.com/pangeo-data/xESMF/pull/395

@ocefpaf, I'm not familiar enough with conda packaging: 
- Would it be a good idea to pin xarray here. A subsequent release of xESMF 0.8.8 would unpin it. Or should we just wait and release 0.8.8 as soon as possible ?
- Can we make the ESMpy pins condition on `importlib_metadata`'s version or something like that ? The issue is that 8.4 is the most recent version windows users can use.

**Comment by ocefpaf** [comment]
> * Would it be a good idea to pin xarray here. A subsequent release of xESMF 0.8.8 would unpin it. Or should we just wait and release 0.8.8 as soon as possible ?

Yes. That or backport that PR as a patch.

> Can we make the ESMpy pins condition on importlib_metadata's version or something like that ? The issue is that 8.4 is the most recent version windows users can use.

Not sure what you mean but if I got it right it will be inconsistent where Windows will be allowed to get the reversion you want to avoid but the other platforms won't. Why is that? What is broken in 8.4 ?

**Comment by aulemahal** [comment]
> it will be inconsistent
I was more thinking of a pin on `importlib_metadata` which would give a way for windows users to still have consistent envs with 8.4. If we continue as in this PR, it is simply forbidden. The issue with windows is because the conda builds of ESMF broke in 8.5 and devs there have not yet been able to fix them.

**Comment by ocefpaf** [comment]
> I was more thinking of a pin on importlib_metadata which would give a way for windows users to still have consistent envs with 8.4. 

I'm not following. Conda doesn't rely on `importlib_metadata` to solve envs. How will thy be inconsistent?

**Comment by aulemahal** [comment]
I'm referring to the issue #43. And you know what, windows users will simply have to install previous versions of xesmf if they want esmf 8.4. I do not have the time and energy to solve this in a fancy way.

**Comment by aulemahal** [comment]
I just released xESMF 0.8.8, I will merge the changes from this branch into the branch updating the conda pacakge.

**Pull request closed without merging**
